feat(ensure methods):  Add update support, sequentially update statefulsets
ava-labs/avalanchego-operator pull request #19
Opened 2022-01-24 12:54 UTC by adutchak

2022-01-24 13:26 UTC, yevhenvolchenko commented on controllers/avalanchego_controller_ensure.go
> +	l.Info("Successfully created a new StatefulSet", commonLogInfo...)
logical error, logger outputs `StatefulSet` despite the actual object type

2022-01-24 13:27 UTC, yevhenvolchenko commented on controllers/avalanchego_controller_ensure.go
> +	l.Info("Creating a new object", commonLogInfo...)
It would be nice to have actual object types in logs

2022-01-24 13:28 UTC, adutchak commented on controllers/avalanchego_controller_ensure.go
> +	l.Info("Successfully created a new StatefulSet", commonLogInfo...)
indeed, fixing it

2022-01-24 13:31 UTC, adutchak commented on controllers/avalanchego_controller_ensure.go
> +	l.Info("Creating a new object", commonLogInfo...)
It is there already: https://github.com/ava-labs/avalanchego-operator/pull/19/files#diff-b635b1e594f16fb6c5e71a5153fd17256b7c4452b1ef59c18cbe5b0cc4bbbd2eR123

`commonLogInfo` slice contains "Type:", targetObj.GetObjectKind().GroupVersionKind().String()

2022-01-24 13:47 UTC, yevhenvolchenko requested changes

2022-01-24 13:47 UTC, yevhenvolchenko commented on controllers/avalanchego_controller_ensure.go
> +		sleepTimeSeconds := 3
looks like constants

2022-01-24 13:47 UTC, yevhenvolchenko commented on controllers/avalanchego_controller_ensure.go
> +		for i := 0; i <= (timeoutSeconds / sleepTimeSeconds); i++ {
compare `resourceVersion`, instead of using timeout

2022-01-25 08:39 UTC, adutchak commented on controllers/avalanchego_controller_ensure.go
> +		sleepTimeSeconds := 3
Moved to constant

2022-01-25 08:40 UTC, adutchak commented on controllers/avalanchego_controller_ensure.go
> +	existed, err := upsertObject(ctx, r, s, true, l)
Moved to constants

2022-01-28 12:57 UTC, yevhenvolchenko approved these changes

2022-01-28 13:04 UTC, merged