feat(logger): improved logger
ava-labs/avalanchego-operator pull request #71
Opened 2022-08-15 22:09 UTC by arturrez

2022-08-15 22:16 UTC, arturrez commented
```
{"level":"info","ts":"2022-08-15T22:06:16.663Z","logger":"controller-runtime.metrics","addr":"127.0.0.1:8080"}
{"level":"info","ts":"2022-08-15T22:06:16.664Z"}
{"level":"info","ts":"2022-08-15T22:06:16.994Z"}
{"level":"info","ts":"2022-08-15T22:06:17.007Z","milliseconds":343,"namespace":"avalanchego-operator-system","service":"avalanchego-operator-webhook-service","secret":"avalanchego-operator-webhook-server-cert"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.builder","GVK":"chain.avax.network/v1alpha1, Kind=Avalanchego"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.builder","GVK":"chain.avax.network/v1alpha1, Kind=Avalanchego","path":"/validate-chain-avax-network-v1alpha1-avalanchego"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.webhook","path":"/validate-chain-avax-network-v1alpha1-avalanchego"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.builder","GVK":"chain.avax.network/v1alpha1, Kind=AvalanchegoValidator"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.builder","GVK":"chain.avax.network/v1alpha1, Kind=AvalanchegoValidator","path":"/validate-chain-avax-network-v1alpha1-avalanchegovalidator"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"controller-runtime.webhook","path":"/validate-chain-avax-network-v1alpha1-avalanchegovalidator"}
{"level":"info","ts":"2022-08-15T22:06:17.008Z","logger":"setup"}
I0815 22:06:17.009039       1 leaderelection.go:243] attempting to acquire leader lease avalanchego-operator-system/ecfcc342.avax.network...
{"level":"info","ts":"2022-08-15T22:06:17.009Z","path":"/metrics"}
{"level":"info","ts":"2022-08-15T22:06:17.009Z","logger":"controller-runtime.webhook.webhooks"}
{"level":"info","ts":"2022-08-15T22:06:17.010Z","logger":"controller-runtime.certwatcher"}
{"level":"info","ts":"2022-08-15T22:06:17.010Z","logger":"controller-runtime.webhook","host":"","port":9443}
{"level":"info","ts":"2022-08-15T22:06:17.048Z","logger":"controller-runtime.certwatcher"}
I0815 22:06:32.694966       1 leaderelection.go:253] successfully acquired lease avalanchego-operator-system/ecfcc342.avax.network
{"level":"info","ts":"2022-08-15T22:06:32.695Z","logger":"controller.avalanchegovalidator","reconciler group":"chain.avax.network","reconciler kind":"AvalanchegoValidator","source":"kind source: /, Kind="}
{"level":"info","ts":"2022-08-15T22:06:32.695Z","logger":"controller.avalanchegovalidator","reconciler group":"chain.avax.network","reconciler kind":"AvalanchegoValidator"}
{"level":"info","ts":"2022-08-15T22:06:32.695Z","logger":"controller.avalanchego","reconciler group":"chain.avax.network","reconciler kind":"Avalanchego","source":"kind source: /, Kind="}
{"level":"info","ts":"2022-08-15T22:06:32.695Z","logger":"controller.avalanchego","reconciler group":"chain.avax.network","reconciler kind":"Avalanchego"}
{"level":"info","ts":"2022-08-15T22:06:32.795Z","logger":"controller.avalanchego","reconciler group":"chain.avax.network","reconciler kind":"Avalanchego","worker count":1}
{"level":"info","ts":"2022-08-15T22:06:32.795Z","logger":"controller.avalanchegovalidator","reconciler group":"chain.avax.network","reconciler kind":"AvalanchegoValidator","worker count":1```
I am not sure why leader election is not picking up logger that we set in `manager` options

2022-08-16 10:55 UTC, adutchak approved these changes

2022-08-16 13:27 UTC, yevhenvolchenko requested changes

2022-08-16 13:27 UTC, yevhenvolchenko commented on controllers/avalanchego_controller.go
> +	l := ctrl.LoggerFrom(ctx)
can we have a single instance per Reconciler?
https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/#creating-a-structured-log-statement

2022-08-16 17:59 UTC, arturrez commented on controllers/utils/logger.go
> +func TextEncoderConfig() zapcore.EncoderConfig {
fixed

2022-08-16 17:59 UTC, arturrez commented on controllers/utils/logger.go
> +func JSONEncoderConfig() zapcore.EncoderConfig {
fixed

2022-08-16 18:56 UTC, arturrez commented on main.go
> -	opts.BindFlags(flag.CommandLine)
fixed

2022-08-16 19:40 UTC, arturrez commented on controllers/avalanchego_controller.go
> +	l := ctrl.LoggerFrom(ctx)
seems like this is what you suggest

2022-08-17 16:50 UTC, yevhenvolchenko approved these changes

2022-08-17 17:25 UTC, merged